sonar.projectKey=zwiggato-backend
sonar.projectName=Zwiggato Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.spec.js

# Language
sonar.language=js

# Test and Coverage
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/test/**,**/tests/**

# Code Quality
sonar.javascript.node=18

